### ISSUE TITLE
sharedUserId changed on newer Android versions

### ISSUE THREAD

**Issue by thebino** [linkedin/test-butler#73] opened 2018-03-15 12:50 UTC
When I try to install the companion app on Android 8.0 or newer, an error occured:
`Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /data/app/com.linkedin.android.testbutler-nLhD7yL27dgN1HH_nNoQDQ==: Package com.linkedin.android.testbutler has no signatures that match those in shared user android.uid.system; ignoring!]`

Looks like, the sharedUserId **android.uid.system** has changed.

**Comment by Kisty** [comment] 2018-03-15 14:59
Duplicate of #71

**Closed** 2018-03-15 15:21 UTC
