### ISSUE TITLE
Gradle plugin to auto install the apk on emulator?

### ISSUE THREAD

**Issue by Kisty** [linkedin/test-butler#22] opened 2016-09-22 12:01 UTC
Would be great if there was a plugin which downloaded and installed the apk prior to running Android tests. Would make set up and CI setup sooo much easier!

**Comment by CristianGM** [comment] 2016-10-19 22:25
This will help #15 to be done

**Comment by cs-victor-nascimento** [comment] 2016-12-28 19:31
This is a task I use in my projects. If requested, I can turn it into a proper Gradle plugin (though there are some subtleties...). The way I am pasting here might be useful for others.

```groovy
final butlerPackage = 'com.linkedin.android.testbutler'
final butlerApkPath = "$rootDir/tools/test-butler/test-butler-app-${rootProject.ext.testButler}.apk"

/**
 * This task installs the test-butler apk in all emulators if needed
 */
task installButlerApk {

    doLast {
        logger.info("Verifying test-butler installation in emulators")

        final adb = "$android.sdkDirectory.absolutePath/platform-tools/adb"

        final String[] split = "$adb devices -l".execute().text.split("\\r?\\n")

        split.each {

            if (it.isEmpty() || !it.startsWith('emulator-'))
                return;

            logger.info("Emulator: $it")

            final emu = it.split("\\s")[0]
            // checks whether the APK is already installed
            if ("$adb -s $emu shell pm list packages".execute().text.contains(butlerPackage))
                return;

            final installResult = "$adb -s $emu install $butlerApkPath".execute().text

            if (!installResult.contains("Success"))
                logger.log(LogLevel.ERROR, "Could not install APK. Install output:\n$installResult")

            else
                logger.info("Installed $butlerApkPath in $emu successfully")
        }
    }
}
```

**Comment by slvn** [comment] 2017-01-17 22:51
My solution is to put this somewhere in a gradle file and to source it if anyone is interested.

```groovy
configurations {
    testButlerApp
}

dependencies {
    testButlerApp 'com.linkedin.testbutler:test-butler-app:1.2.0'
}

def installTestButlerApp() {
    exec {
        executable android.adbExe
        args "install", "-g", "-r", "-d", "-t", configurations.testButlerApp.singleFile
    }
}

android.testVariants.all { variant ->
    variant.connectedInstrumentTest.doFirst {
        installTestButlerApp()
    }
}
```

**Comment by jd-alexander** [comment] 2017-01-24 19:46
@cs-victor-nascimento if you could turn it into a gradle plugin that would be great!

**Comment by cs-victor-nascimento** [comment] 2017-02-17 00:00
@jd-alexander Sorry, but since @drewhannay said they have this on their backlog I won't publish a plugin for this feature because it would quickly (we hope) get deprecated.

I've created a [gist](https://gist.github.com/cs-victor-nascimento/33ccc24395951be1be82bbde1bec9cb4) that includes automatically downloading of the TestButler-app APK per version. It includes some instructions on how to use it. Also, if it helps, I have an archetype like project that has this enabled. [Here is the link](https://github.com/cs-victor-nascimento/cs-android-archetype). It mentions TestButler in the [README](https://github.com/cs-victor-nascimento/cs-android-archetype/blob/master/README.md). Hope it helps until the plugin is released.

**Comment by cs-victor-nascimento** [comment] 2017-05-31 02:26
Just another update to whoever is following this issue. I've just noticed that Test Butler is mentioned in the new android gradle plugin configuration. If you've watched the TDD talk on Google I/O it seems they will be providing an apk for orchestrating test runs in the device/emulator. In order to do that, they've added a new configuration in gradle which the plugin will read and install in the device/emulator prior to running the test suite. 

https://developer.android.com/studio/preview/features/new-android-plugin.html

So, if you are using `3.0.0-alpha1` you can add this configuration:

```groovy
dependencies {
  androidTestUtil 'com.linkedin.testbutler:test-butler-app:1.3.0@apk'
  ...
}
```

**Comment by drewhannay** [comment] 2017-06-07 16:01
This is really awesome. Once AGP 3.0 makes it to the stable channel, I'll update the Test Butler README file with how to use this and then we can (finally) close this issue.

**Comment by IgorGanapolsky** [comment] 2017-08-23 21:20
@cs-victor-nascimento Unfortunately it doesn't work with *1.3.1*.  I get an error:
![screen shot 2017-08-23 at 5 19 38 pm](https://user-images.githubusercontent.com/201209/29639035-4d7518be-8827-11e7-9425-20ad6032d2e2.png)

**Comment by drewhannay** [comment] 2017-08-24 15:13
@IgorGanapolsky What kind of emulator are you using?

**Comment by IgorGanapolsky** [comment] 2017-08-24 15:19
@drewhannay Api 26, x86 emulator with Google Play.  This error actually went away if I use an emulator with Api 25...

**Comment by drewhannay** [comment] 2017-08-24 15:22
That was my guess. The Google Play emulators for API 26 are now signed with a different key, because they include Google Play support (you also won't have root access anymore, IIRC). The AOSP emulator (which has not yet been released for API 26) will still be signed with the test-key and will still work with Test Butler.

**Comment by Tapchicoma** [comment] 2017-11-13 14:41
Actually it is also failing with same reason on emulator without playstore with api 26:

`system-images;android-26;google_apis;x86`

Reason:

```
Caused by: com.android.ddmlib.InstallException: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /data/app/com.linkedin.android.testbutler-BbYyEzpMbbuCNDKyVia5pQ==: Package com.linkedin.android.testbutler has no signatures that match those in shared user android.uid.system; ignoring!
```

**Comment by bootstraponline** [comment] 2017-11-13 14:44
I've had to replace test butler with the espresso grant permission rule. It'd be nice if Google didn't break test butler and offered a work around.

**Comment by Tapchicoma** [comment] 2017-11-13 14:45
But still you also need to disable animations for UI tests and  there is no such Rule 😭

**Comment by bootstraponline** [comment] 2017-11-13 14:47
I know, I love test butler. I don't see how to make it work with the new emulators though. On firebase test lab, they are disabling the animations.

**Comment by Kisty** [comment] 2017-11-13 15:10
For new emulators (`API 26+`), use [`android.testOptions.animationsDisabled`](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.TestOptions.html#com.android.build.gradle.internal.dsl.TestOptions:animationsDisabled). 
For `<API 26`, it disables only view animations, not transition and window animations, I think ([see here](https://twitter.com/zboarda/status/920640208776912897)). Not sure how to conditionally apply test butler for `<API 26`. This would be a workaround for test butler not working with Google Play emulators.

**Comment by bootstraponline** [comment] 2018-02-14 17:53
Anyone know what `animationsDisabled` actually does? Is it simply passing the `--no-window-animation` option to `am instrument`?

**Comment by bootstraponline** [comment] 2018-02-14 18:04
![image](https://user-images.githubusercontent.com/1173057/36220097-76c3601a-1187-11e8-98ca-75c446178eb1.png)
pretty sure it toggles `--no-window-animation` ^

**Comment by lawonga** [comment] 2018-02-14 19:47
Any way to skip `Caused by: com.android.ddmlib.InstallException: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE` when installing on a physical device?

**Comment by Kisty** [comment] 2018-06-19 09:29
@lawonga there isn't currently a workaround (see https://github.com/linkedin/test-butler/issues/22#issuecomment-324668629)

**Closed** 2019-09-10 17:46 UTC

**Comment by orafaaraujo** [comment] 2023-01-18 12:20
Hello 👋 

I added the dependency `"com.linkedin.testbutler:test-butler-app:2.2.1"` but how can I run it and install the apk in my emulator?

Thank you
